### ISSUE TITLE
MissingPluginException

### ISSUE THREAD

**Issue by volgin** [AmudAnan/flutter_path_provider_ex#1]
When starting on iOs:

>Unhandled Exception: MissingPluginException(No implementation found for method getExtStorageData on channel path_provider_ex)

Cleaning, restarting from scratch does not resolve it.

[✓] Flutter (Channel master, v1.13.1-pre.59, on Mac OS X 10.14.6 18G103, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] Connected device (3 available)

**Comment by sc4v3ng3r** [comment]
Also getting this problem.

**Comment by yoavrofe** [comment]
Hi,
iOS is not implemented. I'm considering depreciating this plugin due to errors on Android 10 as well.
